development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redistogo-corrugated-01016") { "redis://pubchatt.herokuapp.com:6379/1" } %>
  channel_prefix: chatapp_production
